version: "3.7"

services:
  app:
    container_name: event-administration-app
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - 3000:3000
    depends_on:
      - mongo
    environment:
      MONGO_HOST: mongo
    command: >
      sh -c "npm run delete:lockfile && npm run build && npm run server:run"

  mongo:
    image: mongo
    command: mongod --quiet --logpath /dev/null
